language: python
python:
  - "3.5"
  - "3.6"
addons:
  apt_packages:
    - pandoc
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - behave
  - ./build.sh